tp/software_engineering2017/s/1/B_17_Martin_Datsev/config/routes.rb
Rails.application.routes.draw do
  resources :subscription_users
  resources :users
  resources :subscriptions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/models/subscription.rb
class Subscription < ApplicationRecord
    has_many :subscription_users
    has_many :users, through: :subscription_users
end

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/models/subscription_user.rb
class SubscriptionUser < ApplicationRecord
    belongs_to :user
    belongs_to :subscription
    validate :sub_limit
    def sub_limit
        if(subscription.price < 10)
            all = SubscriptionUser.all
                .select{|e| e.subscription_id == subscription_id}
                .map{|e| e.position}
            all << position
            teachers = all.select{|e| e == "teacher"}
            students = all.select{|e| e == "student"}
            if(teachers.length > 2)
                errors.add(:subscription_id, "of <10 does not allow more than 2 teachers")
            elsif(students.length > 10)
                errors.add(:subscription_id, "of <10 does not allow more than 10 students")
            end
        end
    end
end

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/models/user.rb
class User < ApplicationRecord
    has_many :subscription_users
    has_many :subscriptions, through: :subscription_users
end

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/controllers/subscription_users_controller.rb
class SubscriptionUsersController < ApplicationController
  before_action :set_subscription_user, only: [:show, :edit, :update, :destroy]

  # GET /subscription_users
  # GET /subscription_users.json
  def index
    @subscription_users = SubscriptionUser.all
  end

  # GET /subscription_users/1
  # GET /subscription_users/1.json
  def show
  end

  # GET /subscription_users/new
  def new
    @subscription_user = SubscriptionUser.new
  end

  # GET /subscription_users/1/edit
  def edit
  end

  # POST /subscription_users
  # POST /subscription_users.json
  def create
    @subscription_user = SubscriptionUser.new(subscription_user_params)

    respond_to do |format|
      if @subscription_user.save
        format.html { redirect_to @subscription_user, notice: 'Subscription user was successfully created.' }
        format.json { render :show, status: :created, location: @subscription_user }
      else
        format.html { render :new }
        format.json { render json: @subscription_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscription_users/1
  # PATCH/PUT /subscription_users/1.json
  def update
    respond_to do |format|
      if @subscription_user.update(subscription_user_params)
        format.html { redirect_to @subscription_user, notice: 'Subscription user was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription_user }
      else
        format.html { render :edit }
        format.json { render json: @subscription_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscription_users/1
  # DELETE /subscription_users/1.json
  def destroy
    @subscription_user.destroy
    respond_to do |format|
      format.html { redirect_to subscription_users_url, notice: 'Subscription user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription_user
      @subscription_user = SubscriptionUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_user_params
      params.require(:subscription_user).permit(:position, :user_id, :subscription_id)
    end
end

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:price)
    end
end

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/helpers/application_helper.rb
module ApplicationHelper
end

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/helpers/subscription_users_helper.rb
module SubscriptionUsersHelper
end

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/helpers/users_helper.rb
module UsersHelper
end

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/views/subscription_users/_form.html.erb
<%= form_with(model: subscription_user, local: true) do |form| %>
  <% if subscription_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription_user.errors.count, "error") %> prohibited this subscription_user from being saved:</h2>

      <ul>
      <% subscription_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position, id: :subscription_user_position %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :subscription_user_user_id %>
  </div>

  <div class="field">
    <%= form.label :subscription_id %>
    <%= form.number_field :subscription_id, id: :subscription_user_subscription_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/views/subscription_users/edit.html.erb
<h1>Editing Subscription User</h1>

<%= render 'form', subscription_user: @subscription_user %>

<%= link_to 'Show', @subscription_user %> |
<%= link_to 'Back', subscription_users_path %>

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/views/subscription_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscription Users</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>User</th>
      <th>Subscription</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscription_users.each do |subscription_user| %>
      <tr>
        <td><%= subscription_user.position %></td>
        <td><%= subscription_user.user_id %></td>
        <td><%= subscription_user.subscription_id %></td>
        <td><%= link_to 'Show', subscription_user %></td>
        <td><%= link_to 'Edit', edit_subscription_user_path(subscription_user) %></td>
        <td><%= link_to 'Destroy', subscription_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription User', new_subscription_user_path %>

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/views/subscription_users/new.html.erb
<h1>New Subscription User</h1>

<%= render 'form', subscription_user: @subscription_user %>

<%= link_to 'Back', subscription_users_path %>

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/views/subscription_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @subscription_user.position %>
</p>

<p>
  <strong>User:</strong>
  <%= @subscription_user.user_id %>
</p>

<p>
  <strong>Subscription:</strong>
  <%= @subscription_user.subscription_id %>
</p>

<%= link_to 'Edit', edit_subscription_user_path(@subscription_user) %> |
<%= link_to 'Back', subscription_users_path %>

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

tp/software_engineering2017/s/1/B_17_Martin_Datsev/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>