tp/p/p2/config/routes.rb
Rails.application.routes.draw do
  resources :programs
  resources :thread_objects, path: 'threads'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

tp/p/p2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tp/p/p2/app/models/program.rb
class Program < ApplicationRecord
    belongs_to :thread_object, foreign_key: 'thread_id', primary_key: 'thread_id'
end

tp/p/p2/app/models/thread_object.rb
class ThreadObject < ApplicationRecord
    has_many :program
end

tp/p/p2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

tp/p/p2/app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:thread_id)
    end
end

tp/p/p2/app/controllers/thread_objects_controller.rb
class ThreadObjectsController < ApplicationController
  before_action :set_thread_object, only: [:show, :edit, :update, :destroy]

  # GET /thread_objects
  # GET /thread_objects.json
  def index
    @thread_objects = ThreadObject.all
  end

  # GET /thread_objects/1
  # GET /thread_objects/1.json
  def show
  end

  # GET /thread_objects/new
  def new
    @thread_object = ThreadObject.new
  end

  # GET /thread_objects/1/edit
  def edit
  end

  # POST /thread_objects
  # POST /thread_objects.json
  def create
    @thread_object = ThreadObject.new(thread_object_params)

    respond_to do |format|
      if @thread_object.save
        format.html { redirect_to @thread_object, notice: 'Thread object was successfully created.' }
        format.json { render :show, status: :created, location: @thread_object }
      else
        format.html { render :new }
        format.json { render json: @thread_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thread_objects/1
  # PATCH/PUT /thread_objects/1.json
  def update
    respond_to do |format|
      if @thread_object.update(thread_object_params)
        format.html { redirect_to @thread_object, notice: 'Thread object was successfully updated.' }
        format.json { render :show, status: :ok, location: @thread_object }
      else
        format.html { render :edit }
        format.json { render json: @thread_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thread_objects/1
  # DELETE /thread_objects/1.json
  def destroy
    @thread_object.destroy
    respond_to do |format|
      format.html { redirect_to thread_objects_url, notice: 'Thread object was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thread_object
      @thread_object = ThreadObject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thread_object_params
      params.require(:thread_object).permit(:thread_id, :value)
    end
end

tp/p/p2/app/helpers/application_helper.rb
module ApplicationHelper
end

tp/p/p2/app/helpers/programs_helper.rb
module ProgramsHelper
end

tp/p/p2/app/helpers/thread_objects_helper.rb
module ThreadObjectsHelper
end

tp/p/p2/app/views/programs/_form.html.erb
<%= form_with(model: program, local: true) do |form| %>
  <% if program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :thread_id %>
    <%= form.number_field :thread_id, id: :program_thread_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tp/p/p2/app/views/programs/edit.html.erb
<h1>Editing Program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

tp/p/p2/app/views/programs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Programs</h1>

<table>
  <thead>
    <tr>
      <th>Thread</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.thread_id %></td>
        <td><%= link_to 'Show', program %></td>
        <td><%= link_to 'Edit', edit_program_path(program) %></td>
        <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program', new_program_path %>

tp/p/p2/app/views/programs/new.html.erb
<h1>New Program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Back', programs_path %>

tp/p/p2/app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Thread:</strong>
  <%= @program.thread_id %>
</p>

<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>